### ISSUE TITLE
support separate quantity on attributes

### ISSUE THREAD

**Issue by Trinity93** [leegarner-glfusion/shop#13]
generally items with different attributes are inventoried in different quantities separately with a separate SKU

**Comment by leegarner** [comment]
I've considered this and it would be possible once the product options part is rewritten. Each permutation of options would need a record containing the quantity.

**Comment by leegarner** [comment]
Moved to v1.1.0 milestone as this relates to #3

**Comment by leegarner** [comment]
Fixed by creating variants for each option combination
