### ISSUE TITLE
internet sales tax laws 

### ISSUE THREAD

**Issue by Trinity93** [leegarner-glfusion/shop#14]
There needs to be a way to determine tax rate rate based on customer address. Some local taxing authorities require sales tax to be charged and remitted for all of their residents even when the vendor is out of state while others only collect sales tax if the customer is local to the vendor or a location owned by the vendor.

**Comment by leegarner** [comment]
Looking into implementing the api from serviceobjects.com. This may be a fairly low-cost solution. Also looking at Avalara which appears to have a free basic plan.

**Comment by Trinity93** [comment]
I can't find any pricing on serviceobjects.com. Beware the "free" options that cost a fortune if used in a real biz setting.

**Comment by leegarner** [comment]
I thought I saw pricing for them, but apparently not. So far I've looked at ServiceObjects, TaxJar, Taxrates.io and Avalara. Only Avalara has a basic free tax API that just supports a couple of methods but would be suited for destination-based tax collection. I'm planning to implement that in a future release as an alternative to the single tax rate (which could still be used in origin-based states).

**Comment by Trinity93** [comment]
The issue is that the laws changed this year with a SCOTUS decision https://www.salestaxinstitute.com/sales_tax_faqs/wayfair-economic-nexus 

This has made sales tax collection a nightmare. As for the origin state only option it's better than nothing for small sellers with only nexus in a single state. It's illegal to charge sales tax where no tax exists or where you are not registered to collect.

**Comment by leegarner** [comment]
If a tax calculation module is added it will not perform complicated tax calculations, it will only return the tax rate for an area subject to the API's accuracy. Some APIs calculate based on source and destination, but those are not being considered.

**Comment by leegarner** [comment]
Planning for 1.1.0. "tax" branch has Avalara and TaxJar enabled, and nexus country/state elements can be added to the plugin configuration.

**Comment by leegarner** [comment]
Fixed in dc6003fa3a343272fbae4229c342086c3797c0b6
