### ISSUE TITLE
pragnation bug

### ISSUE THREAD

**Issue by Trinity93** [leegarner-glfusion/shop#15]
if you have more than the max number of items on a page it does create the page pragnation for new pages but the link does not work to go to the next page

**Comment by leegarner** [comment]
I'll need more information since I'm unable to duplicate the issue with version 0.7.1. What does the "next page" link look like in the catalog view?

(Tested by setting the max products per page to 3 and paging seems to work normally.)

**Comment by Trinity93** [comment]
Whether it works or not seems to be determined by the Homepage Layout setting
http://www.mbbushcraft.com/shop/index.php?category=22 i curently have it set as "Category List (top level)"

**Comment by leegarner** [comment]
I see the issue, this should be fixxed in the last commit. If you want to hot-fix your site before 1.0 is released you can edit plugins/classes/Catalog.class.php and place the new code right after `pagenav_args = array();` around line 181.

**Comment by Trinity93** [comment]
It seems to have fixed it. Thank you.
