### ISSUE TITLE
Products created with Subscription plugin not appearing in the shop catalog on Admin page

### ISSUE THREAD

**Issue by cygnus8929** [leegarner-glfusion/shop#40]
I created a product using the latest Subscription plugin (0.2.3). In the configuration for the Subscription plugin, I have the setting "Show in Shop product catalog?" set to "Yes". When visit the shop as a user (/shop/index.php), the product shows up. However, when I visit the shop as an Admin, no products are present and an error message stating "There are not products in the catalog" is present. I'm not sure if this is desired behavior, so I wanted to flag it just to be sure.

**Comment by leegarner** [comment]
This is actually how it is designed. The admin list pulls only from the Products table; any plugin products are administered from their own admin area.
