### ISSUE TITLE
Address verification redirects back to the cart

### ISSUE THREAD

**Issue by cygnus8929** [leegarner-glfusion/shop#42]
I've configured the Shop (latest version, 1.2.0) plugin to use Smarty Streets. I'm getting the popup to appear during checkout to select either the entered address or the one provided by Smarty Streets. I've verified that Smarty Streets is getting called. I select one of the addresses provided in the popup that appears in the checkout process and I'm redirected back to the cart. The address selected is not being saved to the database. Shouldn't the user be redirected to the order verification page?

I get the same behavior when I use the USPS Web Tools API (enter address -> select verified address -> back to cart).

Also, I could not reset the verification type back to "None". When I select "None" and click submit, the form submits, but the previously selected verification type was listed. I had to change the value in the gl_conf_values table to reset it.

**Comment by leegarner** [comment]
Not sure about this, but I'll leave it open for a bit. It looks like Smartystreets either changed something or their API isn't working correctly as they only return a value if it is matched. Setting the match parameter to "invalid" simply returns the original invalid address. I'll look into the popup redirection, so far I haven't been able to duplicate it.

**Comment by cygnus8929** [comment]
I tested this and it appears to be working properly now.
