### ISSUE TITLE
Add to Cart not working for Subscription products from product detail view

### ISSUE THREAD

**Issue by cygnus8929** [leegarner-glfusion/shop#43]
I've tried both versions (v1 and v2) of the product views. The "Add to Cart" buttons do not work for either one. This is for products in the Shop catalog that were created in the Subscription plugin. The add to cart buttons in the Subscription plugin product page work fine.

When using the v3 of the product list template, the "Add to Cart" button works fine.

**Comment by leegarner** [comment]
Found the issue. There are 4 files that you can update from 60a5eef27798ff155cbf88b813b5004873e1fda9. The problem is that the HTML form ID wasn't valid for plugin product IDs since they have special characters. Sanitizing the IDs first allows it to work.
