### ISSUE TITLE
"(Out of Stock)" reported for product when not tracking quantity

### ISSUE THREAD

**Issue by cygnus8929** [leegarner-glfusion/shop#46]
I created a product in the Shop plugin of "Other Virtual" type. I did not check to box next to "Track Quantity". I noticed 2 potential issues:
1. The product shows up in the catalog with "(Out of Stock)" listed at the bottom of the description.
2. I have another product created in the Subscription plugin. It also has the "(Out of Stock)" label at the bottom of the description.

**Comment by leegarner** [comment]
The issue is that ProductVariant::Validate() is checked for the product, but this doesn't work properly if there are no variants. Changed to calling Product::Validate() for products with no attributes and both now return "OK" regardless of quantity onhand if track_onhand is not set.
